apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chatbot-operator
  template:
    metadata:
      labels:
        name: chatbot-operator
    spec:
      serviceAccountName: chatbot-operator
      containers:
        - name: chatbot-operator
          # Replace this with the built image name
          image: pohsienshih/chatbot-operator:1.0.0
          command:
          - chatbot-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "chatbot-operator"
